language: python

sudo: required

cache:
  pip: true
  directories:
    - $HOME/buildout-cache

python:
  - 2.7

before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - apt-get install rubygems
  - apt-get install graphicsmagick
  - apt-get install poppler-utils
  - gem install docsplit

install:
  - python bootstrap.py -c travis.cfg
  - bin/buildout -Nc travis.cfg

script:
  - bin/code-analysis
  - bin/test

after_success:
  - bin/createcoverage
  - pip install -q coveralls==0.5
  - coveralls

notifications:
  email:
    - martin.peeters@affinitic.be;devs@imio.be
