language: python

sudo: required

cache:
  pip: true
  directories:
    - buildout-cache/downloads
    - buildout-cache/eggs

python:
  - 2.7

before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - sudo apt-get install rubygems
  - sudo apt-get install graphicsmagick
  - sudo apt-get install poppler-utils
  - sudo gem install docsplit
  - sudo apt-get install libreoffice

install:
  - python bootstrap.py --version=2.5.3 --setuptools-version=18.6.1 -c travis.cfg
  - bin/buildout -Nc travis.cfg annotate
  - bin/buildout -Nc travis.cfg

script:
  - bin/code-analysis
  - bin/test

after_success:
  - bin/coverage run bin/test
  - pip install -q coveralls==0.5
  - coveralls

notifications:
  email:
    - martin.peeters@affinitic.be
    - devs@imio.be
